module.exports = {
    CAKE_ORDERED: 'CAKE_ORDERED',
    CAKE_RESTOCK: 'CAKE_RESTOCK',
    ICECREAM_ORDERED: 'ICECREAM_ORDERED',
    ICECREAM_RESTOCK: 'ICECREAM_RESTOCK',
    GET_WORKERS_START: 'GET_WORKERS_START',
    GET_WORKERS_SUCCESS: 'GET_WORKERS_SUCCESS',
    GET_WORKERS_FAILURE: 'GET_WORKERS_FAILURE',
}